name: ultimate_milliseconds
description: Use this package to easily convert various time formats to milliseconds.
version: 0.0.1
homepage: https://justanotherdev.me
repository: https://github.com/nadim1992/ultimate_milliseconds

environment:
  sdk: '>=2.18.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
